"""
Generate portable DDL for a PostgreSQL schema (and optional table subset) for cloning on another cluster.

Uses admin connection + pg_catalog / standard catalogs. Best-effort — exotic types, policies,
partitioning, and replica identity INDEX may need manual follow-up.
"""
from __future__ import annotations

from collections import defaultdict, deque
from typing import Any

import psycopg

from postgres_logical_demo import (
    PUB_DB,
    SUB_DB,
    _RESERVED_HUB_SCHEMAS,
    _validate_pg_identifier,
    _with_db,
)

_MAX_TABLES_PER_EXPORT = 48
_MAX_SQL_CHARS = 450_000


def _quote_ident(cur: psycopg.Cursor, ident: str) -> str:
    cur.execute("SELECT quote_ident(%s)", (ident,))
    return str(cur.fetchone()[0])


def _rel_oid(cur: psycopg.Cursor, schema: str, relname: str) -> int | None:
    cur.execute(
        """
        SELECT c.oid
        FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = %s AND c.relname = %s
        """,
        (schema, relname),
    )
    row = cur.fetchone()
    return int(row[0]) if row else None


def _list_tables(cur: psycopg.Cursor, schema: str) -> list[str]:
    cur.execute(
        """
        SELECT c.relname
        FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = %s AND c.relkind IN ('r')
        ORDER BY c.relname
        """,
        (schema,),
    )
    return [str(r[0]) for r in cur.fetchall()]


def _list_sequences(cur: psycopg.Cursor, schema: str) -> list[str]:
    cur.execute(
        """
        SELECT c.relname
        FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = %s AND c.relkind = 'S'
        ORDER BY c.relname
        """,
        (schema,),
    )
    return [str(r[0]) for r in cur.fetchall()]


def _sequence_ddl(cur: psycopg.Cursor, schema: str, seq: str) -> str:
    """CREATE SEQUENCE … using pg_sequences when available."""
    cur.execute(
        """
        SELECT format_type(s.seqtypid, NULL), s.seqstart, s.seqincrement,
               s.seqmin, s.seqmax, s.seqcycle
        FROM pg_catalog.pg_sequence s
        JOIN pg_catalog.pg_class c ON c.oid = s.seqrelid
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = %s AND c.relname = %s
        """,
        (schema, seq),
    )
    row = cur.fetchone()
    if not row:
        qs = _quote_ident(cur, schema)
        qn = _quote_ident(cur, seq)
        return f"CREATE SEQUENCE IF NOT EXISTS {qs}.{qn};"
    typ, start, inc, vmin, vmax, cycle = row
    qs = _quote_ident(cur, schema)
    qn = _quote_ident(cur, seq)
    cy = "CYCLE" if cycle else "NO CYCLE"
    return (
        f"CREATE SEQUENCE IF NOT EXISTS {qs}.{qn} AS {typ} "
        f"INCREMENT BY {inc} MINVALUE {vmin} MAXVALUE {vmax} "
        f"START {start} {cy};"
    )


def _column_ddl_lines(cur: psycopg.Cursor, schema: str, table: str) -> list[str]:
    cur.execute(
        """
        SELECT a.attname::text,
               pg_catalog.format_type(a.atttypid, a.atttypmod),
               a.attnotnull,
               a.attidentity::text,
               pg_catalog.pg_get_expr(d.adbin, d.adrelid)
        FROM pg_catalog.pg_attribute a
        LEFT JOIN pg_catalog.pg_attrdef d
          ON d.adrelid = a.attrelid AND d.adnum = a.attnum
        JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = %s AND c.relname = %s AND c.relkind = 'r'
          AND a.attnum > 0 AND NOT a.attisdropped
        ORDER BY a.attnum
        """,
        (schema, table),
    )
    lines: list[str] = []
    for name, fmt_type, not_null, identity, def_expr in cur.fetchall():
        qcol = _quote_ident(cur, name)
        parts = [qcol, fmt_type]
        ident = identity or ""
        if ident == "a":
            parts.append("GENERATED ALWAYS AS IDENTITY")
        elif ident == "d":
            parts.append("GENERATED BY DEFAULT AS IDENTITY")
        elif def_expr:
            parts.append(f"DEFAULT {def_expr}")
        if not_null:
            parts.append("NOT NULL")
        lines.append(" ".join(parts))
    return lines


def _table_constraints(
    cur: psycopg.Cursor, schema: str, table: str, contypes: tuple[str, ...]
) -> list[tuple[str, str]]:
    """Return (constraint_name, pg_get_constraintdef) pairs."""
    cur.execute(
        """
        SELECT c.conname::text, pg_catalog.pg_get_constraintdef(c.oid, true)
        FROM pg_catalog.pg_constraint c
        JOIN pg_catalog.pg_class cl ON cl.oid = c.conrelid
        JOIN pg_catalog.pg_namespace n ON n.oid = cl.relnamespace
        WHERE n.nspname = %s AND cl.relname = %s
          AND c.contype = ANY(%s)
        ORDER BY c.contype, c.conname
        """,
        (schema, table, list(contypes)),
    )
    return [(str(r[0]), str(r[1])) for r in cur.fetchall()]


def _replica_identity_sql(cur: psycopg.Cursor, schema: str, table: str) -> str | None:
    cur.execute(
        """
        SELECT c.relreplident::text
        FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = %s AND c.relname = %s AND c.relkind = 'r'
        """,
        (schema, table),
    )
    row = cur.fetchone()
    if not row:
        return None
    rid = row[0]
    qs = _quote_ident(cur, schema)
    qt = _quote_ident(cur, table)
    if rid == "f":
        return f"ALTER TABLE {qs}.{qt} REPLICA IDENTITY FULL;"
    if rid == "n":
        return f"ALTER TABLE {qs}.{qt} REPLICA IDENTITY NOTHING;"
    return None


def _fk_topology_order(
    cur: psycopg.Cursor, schema: str, tables: set[str]
) -> tuple[list[str], bool]:
    """Order tables parent-before-child within ``tables``. Second value True if cycle forced fallback."""
    cur.execute(
        """
        SELECT src.relname::text, tgt.relname::text
        FROM pg_catalog.pg_constraint c
        JOIN pg_catalog.pg_class src ON src.oid = c.conrelid
        JOIN pg_catalog.pg_namespace ns ON ns.oid = src.relnamespace
        JOIN pg_catalog.pg_class tgt ON tgt.oid = c.confrelid
        WHERE ns.nspname = %s AND c.contype = 'f'
          AND src.relkind = 'r'
        """,
        (schema,),
    )
    indeg: dict[str, int] = {t: 0 for t in tables}
    adj: dict[str, list[str]] = defaultdict(list)
    seen: set[tuple[str, str]] = set()
    for child, parent in cur.fetchall():
        if child not in tables or parent not in tables or parent == child:
            continue
        edge = (parent, child)
        if edge in seen:
            continue
        seen.add(edge)
        adj[parent].append(child)
        indeg[child] += 1

    q: deque[str] = deque(sorted(t for t in tables if indeg[t] == 0))
    ordered: list[str] = []
    while q:
        u = q.popleft()
        ordered.append(u)
        for v in sorted(adj.get(u, ())):
            indeg[v] -= 1
            if indeg[v] == 0:
                q.append(v)
    if len(ordered) != len(tables):
        return sorted(tables), True
    return ordered, False


def _view_ddl(cur: psycopg.Cursor, schema: str, view: str) -> str:
    oid = _rel_oid(cur, schema, view)
    if oid is None:
        return ""
    cur.execute("SELECT pg_catalog.pg_get_viewdef(%s::oid, true)", (oid,))
    body = cur.fetchone()[0]
    qs = _quote_ident(cur, schema)
    qv = _quote_ident(cur, view)
    return f"CREATE OR REPLACE VIEW {qs}.{qv} AS\n{body}"


def _matview_ddl(cur: psycopg.Cursor, schema: str, mv: str) -> str:
    oid = _rel_oid(cur, schema, mv)
    if oid is None:
        return ""
    cur.execute("SELECT pg_catalog.pg_get_viewdef(%s::oid, true)", (oid,))
    body = cur.fetchone()[0]
    qs = _quote_ident(cur, schema)
    qm = _quote_ident(cur, mv)
    return f"CREATE MATERIALIZED VIEW IF NOT EXISTS {qs}.{qm} AS\n{body}\nWITH NO DATA;"


def _routine_ddls(cur: psycopg.Cursor, schema: str, kind: str) -> list[str]:
    """kind = 'f' functions, 'p' procedures."""
    cur.execute(
        """
        SELECT p.oid
        FROM pg_catalog.pg_proc p
        JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = %s AND p.prokind = %s
        ORDER BY p.proname
        """,
        (schema, kind),
    )
    out: list[str] = []
    for (oid,) in cur.fetchall():
        cur.execute("SELECT pg_catalog.pg_get_functiondef(%s::oid)", (oid,))
        row = cur.fetchone()
        if row:
            out.append(str(row[0]).rstrip() + ";")
    return out


def export_schema_clone_sql(
    admin_dsn_base: str,
    database: str,
    schema_name: str,
    *,
    table_names: list[str] | None = None,
    include_sequences: bool = True,
    include_tables: bool = True,
    include_views: bool = True,
    include_materialized_views: bool = True,
    include_functions: bool = True,
    include_procedures: bool = True,
    include_grants: bool = False,
) -> dict[str, Any]:
    """
    Build a SQL script to recreate schema objects on another cluster.

    Grants are optional (often cluster-specific). Uses IF NOT EXISTS / OR REPLACE where sensible.
    """
    if database not in (PUB_DB, SUB_DB):
        raise ValueError(f"database must be {PUB_DB!r} or {SUB_DB!r}")
    sch = _validate_pg_identifier(schema_name or "public", ctx="schema")
    if sch in _RESERVED_HUB_SCHEMAS:
        raise ValueError(f"schema {sch!r} cannot be exported from reserved system schemas")

    adm = _with_db(admin_dsn_base, database)
    warnings: list[str] = []
    chunks: list[str] = [
        "-- Generated by mcac-demo-hub schema clone (review before running on production).\n"
        f"-- Source database: {database}\n",
    ]

    subset_mode = bool(table_names)

    with psycopg.connect(adm) as conn:
        with conn.cursor() as cur:
            if sch != "public":
                qs = _quote_ident(cur, sch)
                chunks.append(f"BEGIN;\nCREATE SCHEMA IF NOT EXISTS {qs};\n")
            else:
                chunks.append("BEGIN;\n")

            all_tables = _list_tables(cur, sch)
            chosen = set(all_tables)
            if table_names:
                chosen = set()
                for raw in table_names:
                    chosen.add(_validate_pg_identifier(str(raw).strip(), ctx="table_name"))
                unknown = chosen - set(all_tables)
                if unknown:
                    raise ValueError(
                        "tables not found in schema "
                        f"{sch!r}: {', '.join(sorted(unknown))}"
                    )
            if len(chosen) > _MAX_TABLES_PER_EXPORT:
                raise ValueError(f"at most {_MAX_TABLES_PER_EXPORT} tables per export")

            export_views = include_views and not subset_mode
            export_mviews = include_materialized_views and not subset_mode
            if subset_mode and (include_views or include_materialized_views):
                warnings.append(
                    "Views and materialized views are skipped when a table subset is listed "
                    "(their definitions may reference omitted tables)."
                )

            if include_sequences:
                for seq in _list_sequences(cur, sch):
                    chunks.append(_sequence_ddl(cur, sch, seq) + "\n")

            topo_tables, cyc = _fk_topology_order(cur, sch, chosen)
            if cyc:
                warnings.append(
                    "Foreign-key cycle among selected tables — CREATE TABLE order uses lexical fallback; "
                    "you may need to reorder or split FK ALTER statements."
                )

            table_list = list(topo_tables) if include_tables else []

            for tbl in table_list:
                col_lines = _column_ddl_lines(cur, sch, tbl)
                if not col_lines:
                    warnings.append(f"skipped or empty table definition: {sch}.{tbl}")
                    continue
                qs = _quote_ident(cur, sch)
                qt = _quote_ident(cur, tbl)
                body = ",\n    ".join(col_lines)
                chunks.append(f"CREATE TABLE IF NOT EXISTS {qs}.{qt} (\n    {body}\n);\n")

            # PK, UNIQUE, CHECK (not FK)
            for tbl in table_list:
                qs = _quote_ident(cur, sch)
                qt = _quote_ident(cur, tbl)
                for cn, defn in _table_constraints(cur, sch, tbl, ("p", "u", "c")):
                    qcn = _quote_ident(cur, cn)
                    chunks.append(
                        f"ALTER TABLE ONLY {qs}.{qt} ADD CONSTRAINT {qcn} {defn};\n"
                    )

            # FK last (targets may be outside schema — still emitted)
            for tbl in table_list:
                qs = _quote_ident(cur, sch)
                qt = _quote_ident(cur, tbl)
                for cn, defn in _table_constraints(cur, sch, tbl, ("f",)):
                    qcn = _quote_ident(cur, cn)
                    chunks.append(
                        f"ALTER TABLE ONLY {qs}.{qt} ADD CONSTRAINT {qcn} {defn};\n"
                    )

            for tbl in table_list:
                rif = _replica_identity_sql(cur, sch, tbl)
                if rif:
                    chunks.append(rif + "\n")

            if export_views:
                cur.execute(
                    """
                    SELECT table_name::text
                    FROM information_schema.views
                    WHERE table_schema = %s
                    ORDER BY table_name
                    """,
                    (sch,),
                )
                for (vn,) in cur.fetchall():
                    ddl = _view_ddl(cur, sch, vn)
                    if ddl:
                        chunks.append(ddl.rstrip() + ";\n")

            if export_mviews:
                cur.execute(
                    """
                    SELECT c.relname::text
                    FROM pg_catalog.pg_class c
                    JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
                    WHERE n.nspname = %s AND c.relkind = 'm'
                    ORDER BY c.relname
                    """,
                    (sch,),
                )
                for (mn,) in cur.fetchall():
                    ddl = _matview_ddl(cur, sch, mn)
                    if ddl:
                        chunks.append(ddl + "\n")

            if include_functions:
                chunks.extend(s + "\n" for s in _routine_ddls(cur, sch, "f"))
            if include_procedures:
                chunks.extend(s + "\n" for s in _routine_ddls(cur, sch, "p"))

            if include_grants:
                cur.execute(
                    """
                    SELECT grantee, table_name::text, privilege_type::text
                    FROM information_schema.role_table_grants
                    WHERE table_schema = %s AND grantee NOT IN ('PUBLIC')
                    ORDER BY table_name, privilege_type
                    """,
                    (sch,),
                )
                qs = _quote_ident(cur, sch)
                for grantee, rel, priv in cur.fetchall():
                    qg = _quote_ident(cur, str(grantee))
                    qr = _quote_ident(cur, str(rel))
                    chunks.append(f"GRANT {priv} ON TABLE {qs}.{qr} TO {qg};\n")

    chunks.append("COMMIT;\n")
    sql_text = "".join(chunks)
    if len(sql_text) > _MAX_SQL_CHARS:
        raise ValueError(
            f"generated SQL exceeds {_MAX_SQL_CHARS} characters — narrow table list or disable options"
        )

    return {
        "ok": True,
        "database": database,
        "schema": sch,
        "tables_exported": sorted(chosen) if include_tables else [],
        "warnings": warnings,
        "sql": sql_text,
        "hint": "Run against target cluster after adjusting roles, extensions, and cross-database links; review FK order if referencing tables outside this schema.",
    }
