apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: killrvideo
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-schema
          image: datastax/dse-server:6.7.0
          command: ["/bin/sh", "/scripts/wait.sh"]
          volumeMounts:
            - name: wait-scripts
              mountPath: /scripts
      containers:
        - name: backend
          image: killrvideo/killrvideo-java:3.0.1
          ports:
            - containerPort: 50101
          env:
            - name: KILLRVIDEO_LOGGING_LEVEL
              value: debug
            - name: KILLRVIDEO_DSE_CONTACT_POINTS
              value: dse
          readinessProbe:
            tcpSocket:
              port: 50101
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: wait-scripts
          configMap:
            name: wait-for-keyspace
            defaultMode: 0755
