apiVersion: v1
kind: Service
metadata:
  name: dse
  namespace: killrvideo
  labels:
    app: dse
spec:
  selector:
    app: dse
  ports:
    - name: cql
      port: 9042
      targetPort: 9042
    - name: search
      port: 8983
      targetPort: 8983
    - name: graph
      port: 8182
      targetPort: 8182
