apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: killrvideo

resources:
  - namespace.yaml
  - dse-pvc.yaml
  - wait-for-keyspace.yaml
  - dse-deployment.yaml
  - dse-service.yaml
  - dse-config-job.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - studio-deployment.yaml
  - studio-service.yaml
  - generator-deployment.yaml
