apiVersion: v1
kind: Service
metadata:
  name: studio
  namespace: killrvideo
  labels:
    app: studio
spec:
  type: ClusterIP
  selector:
    app: studio
  ports:
    - name: http
      port: 9091
      targetPort: 9091
