apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: killrvideo
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      initContainers:
        - name: wait-for-backend
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z backend 50101; do
                echo "waiting for backend:50101..."
                sleep 5
              done
      containers:
        - name: web
          image: killrvideo/killrvideo-web:3
          ports:
            - containerPort: 3000
          env:
            - name: KILLRVIDEO_LOGGING_LEVEL
              value: debug
