apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: killrvideo
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z kafka 9092; do
                echo "waiting for kafka:9092..."
                sleep 5
              done
      containers:
        - name: backend
          env:
            - name: KILLRVIDEO_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
